# Meadow.Core pipeline
# Reference: https://aka.ms/yaml

trigger:
- master
- develop

variables:
  solution: '**/Meadow.Core.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  internalFeedName: 'Meadow'
  preReleasePackageBranch: 'refs/heads/develop'

pool:
  vmImage: windows-2019

stages:
- stage: Build
  jobs: 
    - job: Build_Solution
      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: /property:langversion=latest
      - task: CopyFiles@2
        inputs:
          Contents: '**\*.nupkg'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
          cleanTargetFolder: true
          overWrite: true
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: packages

# DEVELOP BRANCH PUBLISH

- stage: Publish_Staging
  dependsOn: Build
  condition: and(succeeded('Build'), eq(variables['build.sourceBranch'], variables['preReleasePackageBranch']))
  jobs:
  - job: Publish_Beta_Nugets
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'packages'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: NuGetCommand@2
        displayName: 'nuget push'
        inputs:
          command: 'push'
          feedsToUse: 'select'
          packagesToPush: '$(System.ArtifactsDirectory)\**\*-*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: $(internalFeedName)
          versioningScheme: 'off'
          allowPackageConflicts: true

# MASTER BRANCH PUBLISH

- stage: Publish_Prod
  dependsOn: Build
  condition: and(succeeded('Build'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Publish_Nugets
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'packages'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: NuGetToolInstaller@1
      - script: nuget push -ApiKey $(meadowNugetApiKey) -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NoSymbols $(System.ArtifactsDirectory)\**\*.nupkg