name: .NET Core CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Core
      uses: actions/checkout@v3
      with:
        path: root # we have to put this in a sub-folder so we can pull Contracts/Units to a parent folde
        
    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop

    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop
    
    - name: Checkout Meadow.Logging side-by-side
      uses: actions/checkout@v2
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          6.0.x
    
    - name: Build Meadow.Core
      run: dotnet build -c Release root/source/Meadow.Core.sln
