name: Develop Build

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout MQTTnet fork
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/MQTTnet
        path: MQTTnet
        ref: meadow
        
    - name: Checkout Meadow.Core
      uses: actions/checkout@v3
      with:
        path: Meadow.Core # we have to put this in a sub-folder so we can pull Contracts/Units to a parent folder
       
    - name: Determine Meadow.Contracts branch to use
      id: pick_contracts_branch
      shell: bash
      env:
        BRANCH: ${{ github.head_ref || github.ref }}
      run: |
        if git ls-remote --exit-code --heads https://github.com/WildernessLabs/Meadow.Contracts ${BRANCH}; then
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
        else
          echo "branch=develop" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: ${{ steps.pick_contracts_branch.outputs.branch }}

    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop

    - name: Checkout Meadow.Modbus
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Modbus
        path: Meadow.Modbus
        ref: develop
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x
          
    - name: apply required VS workloads
      run: dotnet workload restore Meadow.Core/source/Meadow.Core.sln
      
    - name: Build Meadow.Core
      run: dotnet build -c Release Meadow.Core/source/Meadow.Core.sln
    
    - name: Test Core.Unit.Tests
      run: dotnet test -c Release --no-build Meadow.Core/source/Tests/Core.Unit.Tests/Core.Unit.Tests.csproj
